version: '2'
services:
  frontend:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    container_name: twiin-frontend-container
    volumes:
      - .:/app
    # depends_on:
      # - backend
    # env_file:
      # - .env  
    restart: unless-stopped
